# Generated by Django 4.2.7 on 2023-11-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone", models.TextField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=25)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "species",
                    models.IntegerField(choices=[(1, "Cat"), (2, "Dog"), (3, "Bird")]),
                ),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="api.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "Blood Pressure"),
                            (2, "Blood Sugar"),
                            (3, "Blood Oxygen"),
                            (4, "Vaccination"),
                        ]
                    ),
                ),
                ("procedure", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="api.pet",
                    ),
                ),
            ],
        ),
    ]
